// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: backend/api/sdk_protos/metadata.proto

package sdk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Connection config for Metadata store
type MLMDConnectionConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to ConnectionConfig:
	//	*MLMDConnectionConfig_DatabaseConnectionConfig
	//	*MLMDConnectionConfig_MlmdStoreClientConfig
	ConnectionConfig isMLMDConnectionConfig_ConnectionConfig `protobuf_oneof:"connection_config"`
}

func (x *MLMDConnectionConfig) Reset() {
	*x = MLMDConnectionConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_api_sdk_protos_metadata_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MLMDConnectionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MLMDConnectionConfig) ProtoMessage() {}

func (x *MLMDConnectionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_sdk_protos_metadata_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MLMDConnectionConfig.ProtoReflect.Descriptor instead.
func (*MLMDConnectionConfig) Descriptor() ([]byte, []int) {
	return file_backend_api_sdk_protos_metadata_proto_rawDescGZIP(), []int{0}
}

func (m *MLMDConnectionConfig) GetConnectionConfig() isMLMDConnectionConfig_ConnectionConfig {
	if m != nil {
		return m.ConnectionConfig
	}
	return nil
}

func (x *MLMDConnectionConfig) GetDatabaseConnectionConfig() *ConnectionConfig {
	if x, ok := x.GetConnectionConfig().(*MLMDConnectionConfig_DatabaseConnectionConfig); ok {
		return x.DatabaseConnectionConfig
	}
	return nil
}

func (x *MLMDConnectionConfig) GetMlmdStoreClientConfig() *MetadataStoreClientConfig {
	if x, ok := x.GetConnectionConfig().(*MLMDConnectionConfig_MlmdStoreClientConfig); ok {
		return x.MlmdStoreClientConfig
	}
	return nil
}

type isMLMDConnectionConfig_ConnectionConfig interface {
	isMLMDConnectionConfig_ConnectionConfig()
}

type MLMDConnectionConfig_DatabaseConnectionConfig struct {
	DatabaseConnectionConfig *ConnectionConfig `protobuf:"bytes,1,opt,name=database_connection_config,json=databaseConnectionConfig,proto3,oneof"`
}

type MLMDConnectionConfig_MlmdStoreClientConfig struct {
	MlmdStoreClientConfig *MetadataStoreClientConfig `protobuf:"bytes,2,opt,name=mlmd_store_client_config,json=mlmdStoreClientConfig,proto3,oneof"`
}

func (*MLMDConnectionConfig_DatabaseConnectionConfig) isMLMDConnectionConfig_ConnectionConfig() {}

func (*MLMDConnectionConfig_MlmdStoreClientConfig) isMLMDConnectionConfig_ConnectionConfig() {}

// info in workflow IR for cross project producer/consumer workflow.
type MLMDServiceConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Owner             string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name              string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	MlmdServiceTarget string `protobuf:"bytes,3,opt,name=mlmd_service_target,json=mlmdServiceTarget,proto3" json:"mlmd_service_target,omitempty"`
}

func (x *MLMDServiceConfig) Reset() {
	*x = MLMDServiceConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_api_sdk_protos_metadata_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MLMDServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MLMDServiceConfig) ProtoMessage() {}

func (x *MLMDServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_sdk_protos_metadata_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MLMDServiceConfig.ProtoReflect.Descriptor instead.
func (*MLMDServiceConfig) Descriptor() ([]byte, []int) {
	return file_backend_api_sdk_protos_metadata_proto_rawDescGZIP(), []int{1}
}

func (x *MLMDServiceConfig) GetOwner() string {
	if x != nil {
		return x.Owner
	}
	return ""
}

func (x *MLMDServiceConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MLMDServiceConfig) GetMlmdServiceTarget() string {
	if x != nil {
		return x.MlmdServiceTarget
	}
	return ""
}

var File_backend_api_sdk_protos_metadata_proto protoreflect.FileDescriptor

var file_backend_api_sdk_protos_metadata_proto_rawDesc = []byte{
	0x0a, 0x25, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x64,
	0x6b, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x2b, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x64, 0x6b, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f,
	0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf9, 0x01, 0x0a, 0x14, 0x4d, 0x4c, 0x4d, 0x44, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x60, 0x0a,
	0x1a, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x20, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x18, 0x64, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x43,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x64, 0x0a, 0x18, 0x6d, 0x6c, 0x6d, 0x64, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x5f, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x29, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x74, 0x6f,
	0x72, 0x65, 0x2e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x53, 0x74, 0x6f, 0x72, 0x65,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x48, 0x00, 0x52, 0x15,
	0x6d, 0x6c, 0x6d, 0x64, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x13, 0x0a, 0x11, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x4a, 0x04, 0x08, 0x03, 0x10, 0x04,
	0x22, 0x6d, 0x0a, 0x11, 0x4d, 0x4c, 0x4d, 0x44, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x2e, 0x0a, 0x13, 0x6d, 0x6c, 0x6d, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f,
	0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x6d, 0x6c,
	0x6d, 0x64, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x42,
	0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x68,
	0x65, 0x70, 0x6b, 0x6f, 0x79, 0x61, 0x6c, 0x6c, 0x61, 0x6e, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x66,
	0x6c, 0x6f, 0x77, 0x73, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x73, 0x64, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_backend_api_sdk_protos_metadata_proto_rawDescOnce sync.Once
	file_backend_api_sdk_protos_metadata_proto_rawDescData = file_backend_api_sdk_protos_metadata_proto_rawDesc
)

func file_backend_api_sdk_protos_metadata_proto_rawDescGZIP() []byte {
	file_backend_api_sdk_protos_metadata_proto_rawDescOnce.Do(func() {
		file_backend_api_sdk_protos_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(file_backend_api_sdk_protos_metadata_proto_rawDescData)
	})
	return file_backend_api_sdk_protos_metadata_proto_rawDescData
}

var file_backend_api_sdk_protos_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_backend_api_sdk_protos_metadata_proto_goTypes = []interface{}{
	(*MLMDConnectionConfig)(nil),      // 0: MLMDConnectionConfig
	(*MLMDServiceConfig)(nil),         // 1: MLMDServiceConfig
	(*ConnectionConfig)(nil),          // 2: metadata_store.ConnectionConfig
	(*MetadataStoreClientConfig)(nil), // 3: metadata_store.MetadataStoreClientConfig
}
var file_backend_api_sdk_protos_metadata_proto_depIdxs = []int32{
	2, // 0: MLMDConnectionConfig.database_connection_config:type_name -> metadata_store.ConnectionConfig
	3, // 1: MLMDConnectionConfig.mlmd_store_client_config:type_name -> metadata_store.MetadataStoreClientConfig
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_backend_api_sdk_protos_metadata_proto_init() }
func file_backend_api_sdk_protos_metadata_proto_init() {
	if File_backend_api_sdk_protos_metadata_proto != nil {
		return
	}
	file_backend_api_sdk_protos_metadata_store_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_backend_api_sdk_protos_metadata_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MLMDConnectionConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_api_sdk_protos_metadata_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MLMDServiceConfig); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_backend_api_sdk_protos_metadata_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*MLMDConnectionConfig_DatabaseConnectionConfig)(nil),
		(*MLMDConnectionConfig_MlmdStoreClientConfig)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_backend_api_sdk_protos_metadata_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_backend_api_sdk_protos_metadata_proto_goTypes,
		DependencyIndexes: file_backend_api_sdk_protos_metadata_proto_depIdxs,
		MessageInfos:      file_backend_api_sdk_protos_metadata_proto_msgTypes,
	}.Build()
	File_backend_api_sdk_protos_metadata_proto = out.File
	file_backend_api_sdk_protos_metadata_proto_rawDesc = nil
	file_backend_api_sdk_protos_metadata_proto_goTypes = nil
	file_backend_api_sdk_protos_metadata_proto_depIdxs = nil
}
