// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: backend/api/sdk_protos/workflow.proto

package sdk

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Workflow_ExecutionMode int32

const (
	Workflow_EXECUTION_MODE_UNSPECIFIED Workflow_ExecutionMode = 0
	Workflow_SYNC                       Workflow_ExecutionMode = 1
	Workflow_ASYNC                      Workflow_ExecutionMode = 2
)

// Enum value maps for Workflow_ExecutionMode.
var (
	Workflow_ExecutionMode_name = map[int32]string{
		0: "EXECUTION_MODE_UNSPECIFIED",
		1: "SYNC",
		2: "ASYNC",
	}
	Workflow_ExecutionMode_value = map[string]int32{
		"EXECUTION_MODE_UNSPECIFIED": 0,
		"SYNC":                       1,
		"ASYNC":                      2,
	}
)

func (x Workflow_ExecutionMode) Enum() *Workflow_ExecutionMode {
	p := new(Workflow_ExecutionMode)
	*p = x
	return p
}

func (x Workflow_ExecutionMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Workflow_ExecutionMode) Descriptor() protoreflect.EnumDescriptor {
	return file_backend_api_sdk_protos_workflow_proto_enumTypes[0].Descriptor()
}

func (Workflow_ExecutionMode) Type() protoreflect.EnumType {
	return &file_backend_api_sdk_protos_workflow_proto_enumTypes[0]
}

func (x Workflow_ExecutionMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Workflow_ExecutionMode.Descriptor instead.
func (Workflow_ExecutionMode) EnumDescriptor() ([]byte, []int) {
	return file_backend_api_sdk_protos_workflow_proto_rawDescGZIP(), []int{0, 0}
}

type RuntimeParameter_Type int32

const (
	RuntimeParameter_TYPE_UNSPECIFIED RuntimeParameter_Type = 0
	RuntimeParameter_INT              RuntimeParameter_Type = 1
	RuntimeParameter_DOUBLE           RuntimeParameter_Type = 2
	RuntimeParameter_STRING           RuntimeParameter_Type = 3
)

// Enum value maps for RuntimeParameter_Type.
var (
	RuntimeParameter_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "INT",
		2: "DOUBLE",
		3: "STRING",
	}
	RuntimeParameter_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"INT":              1,
		"DOUBLE":           2,
		"STRING":           3,
	}
)

func (x RuntimeParameter_Type) Enum() *RuntimeParameter_Type {
	p := new(RuntimeParameter_Type)
	*p = x
	return p
}

func (x RuntimeParameter_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeParameter_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_backend_api_sdk_protos_workflow_proto_enumTypes[1].Descriptor()
}

func (RuntimeParameter_Type) Type() protoreflect.EnumType {
	return &file_backend_api_sdk_protos_workflow_proto_enumTypes[1]
}

func (x RuntimeParameter_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeParameter_Type.Descriptor instead.
func (RuntimeParameter_Type) EnumDescriptor() ([]byte, []int) {
	return file_backend_api_sdk_protos_workflow_proto_rawDescGZIP(), []int{6, 0}
}

// Definition for a udsl workflow. This is also a definition od a sub workflow
type Workflow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Workflow) Reset() {
	*x = Workflow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_api_sdk_protos_workflow_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Workflow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow) ProtoMessage() {}

func (x *Workflow) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_sdk_protos_workflow_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow.ProtoReflect.Descriptor instead.
func (*Workflow) Descriptor() ([]byte, []int) {
	return file_backend_api_sdk_protos_workflow_proto_rawDescGZIP(), []int{0}
}

// Workflow node definition
type WorkflowNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Basic info of a workflow node
	NodeInfo *NodeInfo `protobuf:"bytes,1,opt,name=node_info,json=nodeInfo,proto3" json:"node_info,omitempty"`
}

func (x *WorkflowNode) Reset() {
	*x = WorkflowNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_api_sdk_protos_workflow_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkflowNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowNode) ProtoMessage() {}

func (x *WorkflowNode) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_sdk_protos_workflow_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowNode.ProtoReflect.Descriptor instead.
func (*WorkflowNode) Descriptor() ([]byte, []int) {
	return file_backend_api_sdk_protos_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *WorkflowNode) GetNodeInfo() *NodeInfo {
	if x != nil {
		return x.NodeInfo
	}
	return nil
}

// Basic information of a workflow node, including the type and id of the node
// The information in `NodeInfo` should stay stable across time. Asynchronous
// data fetching behaviour might change if this changes
type NodeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Metadata type of the node
	Type *ExecutionType `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// The unique identifier of the node within the workflow definition. This id
	// will be used in upstream and downstream nodes to indicate node
	// dependancies. this is generated by the system
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_api_sdk_protos_workflow_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_sdk_protos_workflow_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_backend_api_sdk_protos_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *NodeInfo) GetType() *ExecutionType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *NodeInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Specifications of contexts that this node belongs to. All input artifacts,
// output artifacts and execution of the node will be linked to the (Metadata store)
// contexts generated from these specifications.
type NodeContexts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Contexts []*ContextSpec `protobuf:"bytes,1,rep,name=contexts,proto3" json:"contexts,omitempty"`
}

func (x *NodeContexts) Reset() {
	*x = NodeContexts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_api_sdk_protos_workflow_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeContexts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeContexts) ProtoMessage() {}

func (x *NodeContexts) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_sdk_protos_workflow_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeContexts.ProtoReflect.Descriptor instead.
func (*NodeContexts) Descriptor() ([]byte, []int) {
	return file_backend_api_sdk_protos_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *NodeContexts) GetContexts() []*ContextSpec {
	if x != nil {
		return x.Contexts
	}
	return nil
}

// Spec of a context
type ContextSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The type of the context
	Type *ContextType `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// The name of the context
	Name *IrValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	//properties of the context
	Properties map[string]*IrValue `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ContextSpec) Reset() {
	*x = ContextSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_api_sdk_protos_workflow_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContextSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContextSpec) ProtoMessage() {}

func (x *ContextSpec) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_sdk_protos_workflow_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContextSpec.ProtoReflect.Descriptor instead.
func (*ContextSpec) Descriptor() ([]byte, []int) {
	return file_backend_api_sdk_protos_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *ContextSpec) GetType() *ContextType {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *ContextSpec) GetName() *IrValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *ContextSpec) GetProperties() map[string]*IrValue {
	if x != nil {
		return x.Properties
	}
	return nil
}

// Definition for Value in uDSL IR. A Value instance can be one of: a field
// value that is determined during compilation time, a runtime parameter
// which will be determined during runtime, or a placeholder which will be
// determined during runtime / before / at execution time.
type IrValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//	*IrValue_FieldValue
	//	*IrValue_RuntimeParameter
	//	*IrValue_StructuralRuntimeParameter
	//	*IrValue_Placeholder
	Value isIrValue_Value `protobuf_oneof:"value"`
}

func (x *IrValue) Reset() {
	*x = IrValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_api_sdk_protos_workflow_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IrValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IrValue) ProtoMessage() {}

func (x *IrValue) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_sdk_protos_workflow_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IrValue.ProtoReflect.Descriptor instead.
func (*IrValue) Descriptor() ([]byte, []int) {
	return file_backend_api_sdk_protos_workflow_proto_rawDescGZIP(), []int{5}
}

func (m *IrValue) GetValue() isIrValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *IrValue) GetFieldValue() *Value {
	if x, ok := x.GetValue().(*IrValue_FieldValue); ok {
		return x.FieldValue
	}
	return nil
}

func (x *IrValue) GetRuntimeParameter() *RuntimeParameter {
	if x, ok := x.GetValue().(*IrValue_RuntimeParameter); ok {
		return x.RuntimeParameter
	}
	return nil
}

func (x *IrValue) GetStructuralRuntimeParameter() *StructuralRuntimeParameter {
	if x, ok := x.GetValue().(*IrValue_StructuralRuntimeParameter); ok {
		return x.StructuralRuntimeParameter
	}
	return nil
}

func (x *IrValue) GetPlaceholder() *PlaceholderExpression {
	if x, ok := x.GetValue().(*IrValue_Placeholder); ok {
		return x.Placeholder
	}
	return nil
}

type isIrValue_Value interface {
	isIrValue_Value()
}

type IrValue_FieldValue struct {
	FieldValue *Value `protobuf:"bytes,1,opt,name=field_value,json=fieldValue,proto3,oneof"`
}

type IrValue_RuntimeParameter struct {
	RuntimeParameter *RuntimeParameter `protobuf:"bytes,2,opt,name=runtime_parameter,json=runtimeParameter,proto3,oneof"`
}

type IrValue_StructuralRuntimeParameter struct {
	StructuralRuntimeParameter *StructuralRuntimeParameter `protobuf:"bytes,3,opt,name=structural_runtime_parameter,json=structuralRuntimeParameter,proto3,oneof"`
}

type IrValue_Placeholder struct {
	Placeholder *PlaceholderExpression `protobuf:"bytes,5,opt,name=placeholder,proto3,oneof"`
}

func (*IrValue_FieldValue) isIrValue_Value() {}

func (*IrValue_RuntimeParameter) isIrValue_Value() {}

func (*IrValue_StructuralRuntimeParameter) isIrValue_Value() {}

func (*IrValue_Placeholder) isIrValue_Value() {}

// Definition for a runtime parameters
type RuntimeParameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Required field. The name of the runtime parameter. This should be globally
	// unique within the workflow scope
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Required field. the type of the runtime parameter
	Type RuntimeParameter_Type `protobuf:"varint,2,opt,name=type,proto3,enum=workflow.RuntimeParameter_Type" json:"type,omitempty"`
	// Optional field. Default value of the runtime parameter. If not set and the
	// runtime parameter value is not provided during runtime, an error will be
	// raised.
	DefaultValue *Value `protobuf:"bytes,3,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
}

func (x *RuntimeParameter) Reset() {
	*x = RuntimeParameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_api_sdk_protos_workflow_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RuntimeParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeParameter) ProtoMessage() {}

func (x *RuntimeParameter) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_sdk_protos_workflow_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeParameter.ProtoReflect.Descriptor instead.
func (*RuntimeParameter) Descriptor() ([]byte, []int) {
	return file_backend_api_sdk_protos_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *RuntimeParameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RuntimeParameter) GetType() RuntimeParameter_Type {
	if x != nil {
		return x.Type
	}
	return RuntimeParameter_TYPE_UNSPECIFIED
}

func (x *RuntimeParameter) GetDefaultValue() *Value {
	if x != nil {
		return x.DefaultValue
	}
	return nil
}

// upport structural runtime parameter at the SDK level.
// Definition for structural runtime parameters.
// This can be used to combine several runtime parameters into a single string
// with parts of that being pre-set by users. Consider the following example:
//   `[RuntimeParameter(a), '_some_string_', RuntimeParameter(b)]`
// During runtime, the system will resolve the runtime parameters in the list
// and concatenate all pieces in the list together into a single string.
type StructuralRuntimeParameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parts []*StructuralRuntimeParameter_StringOrRuntimeParameter `protobuf:"bytes,1,rep,name=parts,proto3" json:"parts,omitempty"`
}

func (x *StructuralRuntimeParameter) Reset() {
	*x = StructuralRuntimeParameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_api_sdk_protos_workflow_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StructuralRuntimeParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructuralRuntimeParameter) ProtoMessage() {}

func (x *StructuralRuntimeParameter) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_sdk_protos_workflow_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructuralRuntimeParameter.ProtoReflect.Descriptor instead.
func (*StructuralRuntimeParameter) Descriptor() ([]byte, []int) {
	return file_backend_api_sdk_protos_workflow_proto_rawDescGZIP(), []int{7}
}

func (x *StructuralRuntimeParameter) GetParts() []*StructuralRuntimeParameter_StringOrRuntimeParameter {
	if x != nil {
		return x.Parts
	}
	return nil
}

// A node inside a workflow can be either a  `WorkflowNode` or a `Workflow` as a
// subworkflow
type Workflow_WorkflowOrNode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Node:
	//	*Workflow_WorkflowOrNode_WorkflowNode
	//	*Workflow_WorkflowOrNode_SubWorkflow
	Node isWorkflow_WorkflowOrNode_Node `protobuf_oneof:"node"`
}

func (x *Workflow_WorkflowOrNode) Reset() {
	*x = Workflow_WorkflowOrNode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_api_sdk_protos_workflow_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Workflow_WorkflowOrNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Workflow_WorkflowOrNode) ProtoMessage() {}

func (x *Workflow_WorkflowOrNode) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_sdk_protos_workflow_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Workflow_WorkflowOrNode.ProtoReflect.Descriptor instead.
func (*Workflow_WorkflowOrNode) Descriptor() ([]byte, []int) {
	return file_backend_api_sdk_protos_workflow_proto_rawDescGZIP(), []int{0, 0}
}

func (m *Workflow_WorkflowOrNode) GetNode() isWorkflow_WorkflowOrNode_Node {
	if m != nil {
		return m.Node
	}
	return nil
}

func (x *Workflow_WorkflowOrNode) GetWorkflowNode() *WorkflowNode {
	if x, ok := x.GetNode().(*Workflow_WorkflowOrNode_WorkflowNode); ok {
		return x.WorkflowNode
	}
	return nil
}

func (x *Workflow_WorkflowOrNode) GetSubWorkflow() *Workflow {
	if x, ok := x.GetNode().(*Workflow_WorkflowOrNode_SubWorkflow); ok {
		return x.SubWorkflow
	}
	return nil
}

type isWorkflow_WorkflowOrNode_Node interface {
	isWorkflow_WorkflowOrNode_Node()
}

type Workflow_WorkflowOrNode_WorkflowNode struct {
	// A normal workflow node. This is the unsplittable execution unit
	WorkflowNode *WorkflowNode `protobuf:"bytes,1,opt,name=workflow_node,json=workflowNode,proto3,oneof"`
}

type Workflow_WorkflowOrNode_SubWorkflow struct {
	// sub-workflows should only have execution mode `SYNC`.
	SubWorkflow *Workflow `protobuf:"bytes,2,opt,name=sub_workflow,json=subWorkflow,proto3,oneof"`
}

func (*Workflow_WorkflowOrNode_WorkflowNode) isWorkflow_WorkflowOrNode_Node() {}

func (*Workflow_WorkflowOrNode_SubWorkflow) isWorkflow_WorkflowOrNode_Node() {}

// Definition of each part in the structural runtime parameter. Each part can
// be either a string or a runtime parameter.
type StructuralRuntimeParameter_StringOrRuntimeParameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Value:
	//	*StructuralRuntimeParameter_StringOrRuntimeParameter_ConstantValue
	//	*StructuralRuntimeParameter_StringOrRuntimeParameter_RuntimeParameter
	Value isStructuralRuntimeParameter_StringOrRuntimeParameter_Value `protobuf_oneof:"value"`
}

func (x *StructuralRuntimeParameter_StringOrRuntimeParameter) Reset() {
	*x = StructuralRuntimeParameter_StringOrRuntimeParameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_api_sdk_protos_workflow_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StructuralRuntimeParameter_StringOrRuntimeParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StructuralRuntimeParameter_StringOrRuntimeParameter) ProtoMessage() {}

func (x *StructuralRuntimeParameter_StringOrRuntimeParameter) ProtoReflect() protoreflect.Message {
	mi := &file_backend_api_sdk_protos_workflow_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StructuralRuntimeParameter_StringOrRuntimeParameter.ProtoReflect.Descriptor instead.
func (*StructuralRuntimeParameter_StringOrRuntimeParameter) Descriptor() ([]byte, []int) {
	return file_backend_api_sdk_protos_workflow_proto_rawDescGZIP(), []int{7, 0}
}

func (m *StructuralRuntimeParameter_StringOrRuntimeParameter) GetValue() isStructuralRuntimeParameter_StringOrRuntimeParameter_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (x *StructuralRuntimeParameter_StringOrRuntimeParameter) GetConstantValue() string {
	if x, ok := x.GetValue().(*StructuralRuntimeParameter_StringOrRuntimeParameter_ConstantValue); ok {
		return x.ConstantValue
	}
	return ""
}

func (x *StructuralRuntimeParameter_StringOrRuntimeParameter) GetRuntimeParameter() *RuntimeParameter {
	if x, ok := x.GetValue().(*StructuralRuntimeParameter_StringOrRuntimeParameter_RuntimeParameter); ok {
		return x.RuntimeParameter
	}
	return nil
}

type isStructuralRuntimeParameter_StringOrRuntimeParameter_Value interface {
	isStructuralRuntimeParameter_StringOrRuntimeParameter_Value()
}

type StructuralRuntimeParameter_StringOrRuntimeParameter_ConstantValue struct {
	ConstantValue string `protobuf:"bytes,1,opt,name=constant_value,json=constantValue,proto3,oneof"`
}

type StructuralRuntimeParameter_StringOrRuntimeParameter_RuntimeParameter struct {
	RuntimeParameter *RuntimeParameter `protobuf:"bytes,2,opt,name=runtime_parameter,json=runtimeParameter,proto3,oneof"`
}

func (*StructuralRuntimeParameter_StringOrRuntimeParameter_ConstantValue) isStructuralRuntimeParameter_StringOrRuntimeParameter_Value() {
}

func (*StructuralRuntimeParameter_StringOrRuntimeParameter_RuntimeParameter) isStructuralRuntimeParameter_StringOrRuntimeParameter_Value() {
}

var File_backend_api_sdk_protos_workflow_proto protoreflect.FileDescriptor

var file_backend_api_sdk_protos_workflow_proto_rawDesc = []byte{
	0x0a, 0x25, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x64,
	0x6b, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f,
	0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f,
	0x77, 0x1a, 0x2b, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73,
	0x64, 0x6b, 0x5f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x28,
	0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x64, 0x6b, 0x5f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xe3, 0x01, 0x0a, 0x08, 0x57, 0x6f, 0x72,
	0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x1a, 0x90, 0x01, 0x0a, 0x0e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c,
	0x6f, 0x77, 0x4f, 0x72, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x3d, 0x0a, 0x0d, 0x77, 0x6f, 0x72, 0x6b,
	0x66, 0x6c, 0x6f, 0x77, 0x5f, 0x6e, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x66,
	0x6c, 0x6f, 0x77, 0x4e, 0x6f, 0x64, 0x65, 0x48, 0x00, 0x52, 0x0c, 0x77, 0x6f, 0x72, 0x6b, 0x66,
	0x6c, 0x6f, 0x77, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x37, 0x0a, 0x0c, 0x73, 0x75, 0x62, 0x5f, 0x77,
	0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e,
	0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f,
	0x77, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x75, 0x62, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77,
	0x42, 0x06, 0x0a, 0x04, 0x6e, 0x6f, 0x64, 0x65, 0x22, 0x44, 0x0a, 0x0d, 0x45, 0x78, 0x65, 0x63,
	0x75, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x1e, 0x0a, 0x1a, 0x45, 0x58, 0x45,
	0x43, 0x55, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4d, 0x4f, 0x44, 0x45, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x53, 0x59, 0x4e,
	0x43, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x53, 0x59, 0x4e, 0x43, 0x10, 0x02, 0x22, 0x3f,
	0x0a, 0x0c, 0x57, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x2f,
	0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x4e, 0x6f, 0x64,
	0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x22,
	0x4d, 0x0a, 0x08, 0x4e, 0x6f, 0x64, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x31, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x45, 0x78, 0x65, 0x63, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x41,
	0x0a, 0x0c, 0x4e, 0x6f, 0x64, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x73, 0x12, 0x31,
	0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x53, 0x70, 0x65, 0x63, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x73, 0x22, 0xfe, 0x01, 0x0a, 0x0b, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x53, 0x70, 0x65,
	0x63, 0x12, 0x2f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1b, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65,
	0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x49, 0x72, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x45, 0x0a, 0x0a, 0x70, 0x72, 0x6f,
	0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e,
	0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74,
	0x53, 0x70, 0x65, 0x63, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x0a, 0x70, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73,
	0x1a, 0x50, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x69, 0x65, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x27, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e,
	0x49, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02,
	0x38, 0x01, 0x22, 0xbd, 0x02, 0x0a, 0x07, 0x49, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x38,
	0x0a, 0x0b, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x73,
	0x74, 0x6f, 0x72, 0x65, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48, 0x00, 0x52, 0x0a, 0x66, 0x69,
	0x65, 0x6c, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x49, 0x0a, 0x11, 0x72, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x52,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x48,
	0x00, 0x52, 0x10, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x12, 0x68, 0x0a, 0x1c, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x61,
	0x6c, 0x5f, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65,
	0x74, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x77, 0x6f, 0x72, 0x6b,
	0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x61, 0x6c, 0x52,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x48,
	0x00, 0x52, 0x1a, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x61, 0x6c, 0x52, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x3a, 0x0a,
	0x0b, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x16, 0x2e, 0x50, 0x6c, 0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72,
	0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0b, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x68, 0x6f, 0x6c, 0x64, 0x65, 0x72, 0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x22, 0xd6, 0x01, 0x0a, 0x10, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x33, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f, 0x2e, 0x77, 0x6f, 0x72, 0x6b,
	0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x65, 0x74, 0x65, 0x72, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x3a, 0x0a, 0x0d, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x5f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x2e, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52, 0x0c,
	0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x3d, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x10, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x49, 0x4e,
	0x54, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x4f, 0x55, 0x42, 0x4c, 0x45, 0x10, 0x02, 0x12,
	0x0a, 0x0a, 0x06, 0x53, 0x54, 0x52, 0x49, 0x4e, 0x47, 0x10, 0x03, 0x22, 0x8b, 0x02, 0x0a, 0x1a,
	0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x61, 0x6c, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d,
	0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x53, 0x0a, 0x05, 0x70, 0x61,
	0x72, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3d, 0x2e, 0x77, 0x6f, 0x72, 0x6b,
	0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x61, 0x6c, 0x52,
	0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x2e,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4f, 0x72, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x50,
	0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x52, 0x05, 0x70, 0x61, 0x72, 0x74, 0x73, 0x1a,
	0x97, 0x01, 0x0a, 0x18, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4f, 0x72, 0x52, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x27, 0x0a, 0x0e,
	0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x74,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x49, 0x0a, 0x11, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65,
	0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x2e, 0x52, 0x75, 0x6e, 0x74,
	0x69, 0x6d, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x10,
	0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x42, 0x07, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x68, 0x65, 0x70, 0x6b, 0x6f, 0x79, 0x61,
	0x6c, 0x6c, 0x61, 0x6e, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x66, 0x6c, 0x6f, 0x77, 0x73, 0x2f, 0x62,
	0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x64, 0x6b, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_backend_api_sdk_protos_workflow_proto_rawDescOnce sync.Once
	file_backend_api_sdk_protos_workflow_proto_rawDescData = file_backend_api_sdk_protos_workflow_proto_rawDesc
)

func file_backend_api_sdk_protos_workflow_proto_rawDescGZIP() []byte {
	file_backend_api_sdk_protos_workflow_proto_rawDescOnce.Do(func() {
		file_backend_api_sdk_protos_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(file_backend_api_sdk_protos_workflow_proto_rawDescData)
	})
	return file_backend_api_sdk_protos_workflow_proto_rawDescData
}

var file_backend_api_sdk_protos_workflow_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_backend_api_sdk_protos_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_backend_api_sdk_protos_workflow_proto_goTypes = []interface{}{
	(Workflow_ExecutionMode)(0),        // 0: workflow.Workflow.ExecutionMode
	(RuntimeParameter_Type)(0),         // 1: workflow.RuntimeParameter.Type
	(*Workflow)(nil),                   // 2: workflow.Workflow
	(*WorkflowNode)(nil),               // 3: workflow.WorkflowNode
	(*NodeInfo)(nil),                   // 4: workflow.NodeInfo
	(*NodeContexts)(nil),               // 5: workflow.NodeContexts
	(*ContextSpec)(nil),                // 6: workflow.ContextSpec
	(*IrValue)(nil),                    // 7: workflow.IrValue
	(*RuntimeParameter)(nil),           // 8: workflow.RuntimeParameter
	(*StructuralRuntimeParameter)(nil), // 9: workflow.StructuralRuntimeParameter
	(*Workflow_WorkflowOrNode)(nil),    // 10: workflow.Workflow.WorkflowOrNode
	nil,                                // 11: workflow.ContextSpec.PropertiesEntry
	(*StructuralRuntimeParameter_StringOrRuntimeParameter)(nil), // 12: workflow.StructuralRuntimeParameter.StringOrRuntimeParameter
	(*ExecutionType)(nil),         // 13: metadata_store.ExecutionType
	(*ContextType)(nil),           // 14: metadata_store.ContextType
	(*Value)(nil),                 // 15: metadata_store.Value
	(*PlaceholderExpression)(nil), // 16: PlaceholderExpression
}
var file_backend_api_sdk_protos_workflow_proto_depIdxs = []int32{
	4,  // 0: workflow.WorkflowNode.node_info:type_name -> workflow.NodeInfo
	13, // 1: workflow.NodeInfo.type:type_name -> metadata_store.ExecutionType
	6,  // 2: workflow.NodeContexts.contexts:type_name -> workflow.ContextSpec
	14, // 3: workflow.ContextSpec.type:type_name -> metadata_store.ContextType
	7,  // 4: workflow.ContextSpec.name:type_name -> workflow.IrValue
	11, // 5: workflow.ContextSpec.properties:type_name -> workflow.ContextSpec.PropertiesEntry
	15, // 6: workflow.IrValue.field_value:type_name -> metadata_store.Value
	8,  // 7: workflow.IrValue.runtime_parameter:type_name -> workflow.RuntimeParameter
	9,  // 8: workflow.IrValue.structural_runtime_parameter:type_name -> workflow.StructuralRuntimeParameter
	16, // 9: workflow.IrValue.placeholder:type_name -> PlaceholderExpression
	1,  // 10: workflow.RuntimeParameter.type:type_name -> workflow.RuntimeParameter.Type
	15, // 11: workflow.RuntimeParameter.default_value:type_name -> metadata_store.Value
	12, // 12: workflow.StructuralRuntimeParameter.parts:type_name -> workflow.StructuralRuntimeParameter.StringOrRuntimeParameter
	3,  // 13: workflow.Workflow.WorkflowOrNode.workflow_node:type_name -> workflow.WorkflowNode
	2,  // 14: workflow.Workflow.WorkflowOrNode.sub_workflow:type_name -> workflow.Workflow
	7,  // 15: workflow.ContextSpec.PropertiesEntry.value:type_name -> workflow.IrValue
	8,  // 16: workflow.StructuralRuntimeParameter.StringOrRuntimeParameter.runtime_parameter:type_name -> workflow.RuntimeParameter
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_backend_api_sdk_protos_workflow_proto_init() }
func file_backend_api_sdk_protos_workflow_proto_init() {
	if File_backend_api_sdk_protos_workflow_proto != nil {
		return
	}
	file_backend_api_sdk_protos_metadata_store_proto_init()
	file_backend_api_sdk_protos_placeholder_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_backend_api_sdk_protos_workflow_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Workflow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_api_sdk_protos_workflow_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkflowNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_api_sdk_protos_workflow_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_api_sdk_protos_workflow_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeContexts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_api_sdk_protos_workflow_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContextSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_api_sdk_protos_workflow_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IrValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_api_sdk_protos_workflow_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RuntimeParameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_api_sdk_protos_workflow_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StructuralRuntimeParameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_api_sdk_protos_workflow_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Workflow_WorkflowOrNode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_api_sdk_protos_workflow_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StructuralRuntimeParameter_StringOrRuntimeParameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_backend_api_sdk_protos_workflow_proto_msgTypes[5].OneofWrappers = []interface{}{
		(*IrValue_FieldValue)(nil),
		(*IrValue_RuntimeParameter)(nil),
		(*IrValue_StructuralRuntimeParameter)(nil),
		(*IrValue_Placeholder)(nil),
	}
	file_backend_api_sdk_protos_workflow_proto_msgTypes[8].OneofWrappers = []interface{}{
		(*Workflow_WorkflowOrNode_WorkflowNode)(nil),
		(*Workflow_WorkflowOrNode_SubWorkflow)(nil),
	}
	file_backend_api_sdk_protos_workflow_proto_msgTypes[10].OneofWrappers = []interface{}{
		(*StructuralRuntimeParameter_StringOrRuntimeParameter_ConstantValue)(nil),
		(*StructuralRuntimeParameter_StringOrRuntimeParameter_RuntimeParameter)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_backend_api_sdk_protos_workflow_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_backend_api_sdk_protos_workflow_proto_goTypes,
		DependencyIndexes: file_backend_api_sdk_protos_workflow_proto_depIdxs,
		EnumInfos:         file_backend_api_sdk_protos_workflow_proto_enumTypes,
		MessageInfos:      file_backend_api_sdk_protos_workflow_proto_msgTypes,
	}.Build()
	File_backend_api_sdk_protos_workflow_proto = out.File
	file_backend_api_sdk_protos_workflow_proto_rawDesc = nil
	file_backend_api_sdk_protos_workflow_proto_goTypes = nil
	file_backend_api_sdk_protos_workflow_proto_depIdxs = nil
}
